# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
# 모델링: Sequential API

# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 553ms/step - loss: 686.9184
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 686.2919
Epoch 3/10
1/1 [==============================] - 0s 19ms/step - loss: 685.6656
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 685.0397
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 684.4142
Epoch 6/10
1/1 [==============================] - 0s 16ms/step - loss: 683.7888
Epoch 7/10
1/1 [==============================] - 0s 21ms/step - loss: 683.1638
Epoch 8/10
1/1 [==============================] - 0s 21ms/step - loss: 682.5392
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 681.9147
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 681.2906


In [ ]:
# 결과 출력해줘!
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1,) )

[0.        1.1356283 2.2712567 3.4068851 4.5425134]


In [ ]:
y[:5].reshape(-1)

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [ ]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
# 모델링: Sequential API

# 1. 세션 클리어(기존 모델 제거)
keras.backend.clear_session()

# 2. 레이어를 쌓을 발판(Sequential())
model = keras.models.Sequential()

# 3. 레이어 블록 조립(.add())
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 4. 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 학습
hist = model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 499ms/step - loss: 626.9744
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 626.3937
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 625.8130
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 625.2328
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 624.6530
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 624.0734
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 623.4941
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 622.9152
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 622.3365
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 621.7582


In [ ]:
#hist.history['loss'][-1]

621.7581787109375

In [ ]:
#model.evaluate(x, y, verbose=1)

1/1 [==============================] - 0s 105ms/step - loss: 621.1802


621.1802368164062

In [ ]:
# 예측값 생성
y_pred = model.predict(x)
y_pred[:5]

array([[-0.00999813],
       [-0.04651644],
       [-0.08303474],
       [-0.11955304],
       [-0.15607135]], dtype=float32)

In [ ]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [57]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [58]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [59]:
x.shape, y.shape

((20,), (20,))

In [60]:
# 모델링: Sequential API

# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 레이어 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [61]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 402ms/step - loss: 3.0700 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 3.0673 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 3.0646 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 3.0619 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 3.0592 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 3.0565 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 3.0538 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 3.0511 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 3.0484 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 3.0458 - accuracy: 0.5500


In [63]:
# 예측
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

array([0.49750012, 0.78949153, 0.93424034, 0.9817575 , 0.99511874],
      dtype=float32)

In [64]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [70]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [72]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [73]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 모델 선언
model = keras.models.Sequential()

# 3. 모델 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 5ms/step - loss: 7.8248 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 5ms/step - loss: 7.8146 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 4ms/step - loss: 7.8051 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 7.7947 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 7.7845 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 4ms/step - loss: 7.7738 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 5ms/step - loss: 7.7642 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 7.7545 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 7.7444 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 5ms/step - loss: 7.7335 - accuracy: 0.5250


In [75]:
y_pred = model.predict(x)

In [76]:
for idx, val in enumerate(y_pred):
  if val >= 0.5:
    y_pred[idx] = 1
  else:
    y_pred[idx] = 0

In [77]:
y_pred[:5]

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [78]:
y[:5]

array([0, 0, 0, 0, 0])