# Keras로 Linear&Logistic Regression 맛보기!

### Kaggle Link for exercise :
* [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) : 

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [5]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [7]:
x = np.array(range(0,20))
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [8]:
x.shape, y.shape

((20,), (20,))

In [10]:
# 모델링: Funtional API

# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어를 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='linear')(il)

# 3. 레이어 지정
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [11]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 645ms/step - loss: 521.2106
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 520.6650
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 520.1197
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 519.5746
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 519.0299
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 518.4855
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 517.9413
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 517.3976
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 516.8541
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 516.3109


In [12]:
# 예측
y_pred = model.predict(x)
print(y_pred[:5].reshape(-1,) )

[ 0.00999823 -0.11073983 -0.23147787 -0.35221592 -0.47295398]


In [13]:
y[:5].reshape(-1)

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [24]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [25]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [26]:
x.shape, y.shape

((20,), (20,))

In [46]:
# 모델링: Funtional API

# 1. 세션 클리어(기존 모델 제거)
keras.backend.clear_session()

# 2. 레이어를 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3. 모델의 시작과 끝 지정(레이어 지정)
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [28]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 310ms/step - loss: 1257.7361
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 1256.9020
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 1256.0681
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 1255.2345
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 1254.4011
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 1253.5681
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 1252.7355
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 1251.9031
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 1251.0709
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 1250.2394


In [29]:
# 예측값 생성
y_pred = model.predict(x)
y_pred[:5]

array([[-0.00999875],
       [ 0.90614593],
       [ 1.8222905 ],
       [ 2.7384353 ],
       [ 3.6545799 ]], dtype=float32)

In [30]:
y[:5]

array([10,  7,  4,  1, -2])

In [ ]:
model.add(keras.layers.Input(shape=(2,)))
model.add(keras.layers.Dense(1,))

## Quick Logistic Regression!

In [31]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [32]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [33]:
x.shape, y.shape

((20,), (20,))

In [34]:
# 모델링: Functional API

# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어를 사슬처럼 엮기
a = keras.layers.Input(shape=(1,))
b = keras.layers.Dense(1, activation='sigmoid')(a)

# 3. 레이어 지정
model = keras.models.Model(a, b)

# 4. 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [35]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 461ms/step - loss: 11.4051 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 11.3974 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 11.3897 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 11.3820 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 16ms/step - loss: 11.3743 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 11.3666 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 11.3589 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 11.3512 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 11.3435 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 11.3358 - accuracy: 0.4500


In [36]:
# 예측
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

array([0.5024999 , 0.17556992, 0.0429709 , 0.00937799, 0.00199202],
      dtype=float32)

In [37]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [38]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [39]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [40]:
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어 설정
a = keras.layers.Input(shape=(1,))
b = keras.layers.Dense(1, activation='sigmoid')(a)

# 3. 레이어 지정
model = keras.models.Model(a, b)

# 4. 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [41]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 6.1090 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 8ms/step - loss: 6.0988 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 5ms/step - loss: 6.0884 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 9ms/step - loss: 6.0785 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 6.0686 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 6ms/step - loss: 6.0590 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 6.0484 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 6.0395 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 6.0296 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 12ms/step - loss: 6.0195 - accuracy: 0.5250


In [42]:
y_pred = model.predict(x)

In [43]:
for idx, val in enumerate(y_pred):
  if val >= 0.5:
    y_pred[idx] = 1
  else:
    y_pred[idx] = 0

In [44]:
y_pred[:5]

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [45]:
y[:5]

array([0, 0, 0, 0, 0])