# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [7]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [8]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [9]:
keras.backend.clear_session()

a = keras.layers.Input(shape=(13,))
b = keras.layers.Dense(1)(a)

model = keras.models.Model(a,b)

model.compile(loss='mse', optimizer='adam')

In [10]:
model.fit(x, y, epochs=20, verbose=1)

Epoch 1/20
16/16 [==============================] - 0s 2ms/step - loss: 15442.4287
Epoch 2/20
16/16 [==============================] - 0s 2ms/step - loss: 12472.3105
Epoch 3/20
16/16 [==============================] - 0s 2ms/step - loss: 10056.1719
Epoch 4/20
16/16 [==============================] - 0s 2ms/step - loss: 8125.7935
Epoch 5/20
16/16 [==============================] - 0s 2ms/step - loss: 6671.7310
Epoch 6/20
16/16 [==============================] - 0s 2ms/step - loss: 5567.4443
Epoch 7/20
16/16 [==============================] - 0s 2ms/step - loss: 4783.4307
Epoch 8/20
16/16 [==============================] - 0s 2ms/step - loss: 4221.6738
Epoch 9/20
16/16 [==============================] - 0s 2ms/step - loss: 3797.0212
Epoch 10/20
16/16 [==============================] - 0s 2ms/step - loss: 3487.8870
Epoch 11/20
16/16 [==============================] - 0s 2ms/step - loss: 3271.1877
Epoch 12/20
16/16 [==============================] - 0s 2ms/step - loss: 3092.3340
Epoch 13/2

In [11]:
y_pred = model.predict(x)
print(y_pred[:5])

[[55.68037 ]
 [79.85142 ]
 [67.01542 ]
 [63.666374]
 [69.94189 ]]


In [12]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [13]:
from sklearn.datasets import load_breast_cancer

In [14]:
cancer = load_breast_cancer()

In [15]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [16]:
keras.backend.clear_session()

a = keras.layers.Input(shape=(30,))
b = keras.layers.Dense(1, activation='sigmoid')(a)

model = keras.models.Model(a,b)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 3ms/step - loss: 137.2931 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 4ms/step - loss: 118.3995 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 3ms/step - loss: 99.8149 - accuracy: 0.6274
Epoch 4/10
18/18 [==============================] - 0s 3ms/step - loss: 81.2927 - accuracy: 0.6274
Epoch 5/10
18/18 [==============================] - 0s 3ms/step - loss: 62.6559 - accuracy: 0.6274
Epoch 6/10
18/18 [==============================] - 0s 3ms/step - loss: 44.5933 - accuracy: 0.6186
Epoch 7/10
18/18 [==============================] - 0s 3ms/step - loss: 28.9266 - accuracy: 0.3884
Epoch 8/10
18/18 [==============================] - 0s 3ms/step - loss: 21.3185 - accuracy: 0.1213
Epoch 9/10
18/18 [==============================] - 0s 3ms/step - loss: 19.9684 - accuracy: 0.1213
Epoch 10/10
18/18 [==============================] - 0s 3ms/step - loss: 19.3152 - accuracy: 0.1230


In [19]:
y_pred = model.predict(x)
for i, j in enumerate(y_pred):
  if j >= 0.5:
    y_pred[i] = 1
  else:
    y_pred[i] = 0
y_pred[:5]

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [20]:
y[:5]

array([0, 0, 0, 0, 0])