<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

# 실습 내용

- Iris 데이터로 모델링합니다.
- Logistic Regression 알고리즘으로 모델링합니다.


# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [39]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%config InlineBackend.figure_format='retina'

In [40]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/iris.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [41]:
# 상위 몇 개 행 확인
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
# 기초통계량 확인
data.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [43]:
# 범주값 개수 확인
data['Species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: Species, dtype: int64

In [44]:
# 상관관계 확인
data.corr()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.000000    -0.117570      0.871754     0.817941
Sepal.Width      -0.117570     1.000000     -0.428440    -0.366126
Petal.Length      0.871754    -0.428440      1.000000     0.962865
Petal.Width       0.817941    -0.366126      0.962865     1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) x, y 분리**

In [45]:
# target 확인
target = 'Species'

# 데이터 분리
x = data.drop(target, axis=1)
y = data[target]

**2) 학습용, 평가용 데이터 분리**

In [46]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2022)

# 4.모델링

- 본격적으로 모델을 **선언**하고 **학습**하고 **평가**하는 과정을 진행합니다.

In [47]:
# 1단계: 불러오기
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

In [48]:
# 2단계: 선언하기
model = LogisticRegression(max_iter=500)

In [49]:
# 3단계: 학습하기
model.fit(x_train, y_train)

LogisticRegression(max_iter=500)

In [50]:
# 4단계: 예측하기
y_pred = model.predict(x_test)

In [51]:
# 5단계 평가하기
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.94      1.00      0.97        15
   virginica       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



# 5.(옵션)모델 들여다 보기

In [52]:
# 가중치, 편향 확인
print(list(x))
print(model.coef_)
print(model.intercept_)

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']
[[-0.39229326  0.85677362 -2.233365   -0.98443734]
 [ 0.558705   -0.25249701 -0.11346233 -0.90531565]
 [-0.16641174 -0.60427662  2.34682734  1.889753  ]]
[  8.8505434    1.21891531 -10.0694587 ]


In [53]:
# z값 확인
z = model.decision_function(x_test)
print(z[:10].round(2))

[[-5.84  1.55  4.28]
 [-8.37  2.06  6.31]
 [ 5.85  2.76 -8.61]
 [-5.06  1.76  3.3 ]
 [ 6.43  2.75 -9.18]
 [ 6.29  2.61 -8.89]
 [ 0.04  2.44 -2.49]
 [-0.82  2.26 -1.44]
 [ 6.52  2.84 -9.37]
 [-1.25  2.41 -1.15]]


In [54]:
# softmax 함수 값 확인
from scipy.special import expit
print(expit(z)[:10].round(2))

[[0.   0.83 0.99]
 [0.   0.89 1.  ]
 [1.   0.94 0.  ]
 [0.01 0.85 0.96]
 [1.   0.94 0.  ]
 [1.   0.93 0.  ]
 [0.51 0.92 0.08]
 [0.31 0.91 0.19]
 [1.   0.95 0.  ]
 [0.22 0.92 0.24]]


In [55]:
# p값 확인
p = model.predict_proba(x_test)
print(p[:10].round(2))

[[0.   0.06 0.94]
 [0.   0.01 0.99]
 [0.96 0.04 0.  ]
 [0.   0.18 0.82]
 [0.98 0.02 0.  ]
 [0.98 0.02 0.  ]
 [0.08 0.91 0.01]
 [0.04 0.93 0.02]
 [0.98 0.02 0.  ]
 [0.02 0.95 0.03]]


In [56]:
# softmax 함수 값 확인
from scipy.special import softmax
print(softmax(z, axis=1)[:10].round(2))

[[0.   0.06 0.94]
 [0.   0.01 0.99]
 [0.96 0.04 0.  ]
 [0.   0.18 0.82]
 [0.98 0.02 0.  ]
 [0.98 0.02 0.  ]
 [0.08 0.91 0.01]
 [0.04 0.93 0.02]
 [0.98 0.02 0.  ]
 [0.02 0.95 0.03]]


In [57]:
# 가장 큰 값의 인덱스 확인
print(p[:10].argmax(axis=1))

[2 2 0 2 0 0 1 1 0 1]


In [58]:
# 가장 큰 값의 인덱스 - 클래스 이름으로 확인
[y.unique()[x] for x in p[:10].argmax(axis=1)]

['virginica',
 'virginica',
 'setosa',
 'virginica',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'setosa',
 'versicolor']

In [59]:
# 예측값 확인
print(y_pred[:10])

['virginica' 'virginica' 'setosa' 'virginica' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'setosa' 'versicolor']
